name: Build
on:
  pull_request:
    branches: ["master"]
  push:
  workflow_dispatch:
jobs:

  build-uwebsockets-mac: 
    name: Build uWebSockets (macOS)
    runs-on: macos-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3.6.0
      with:
        repository: uNetworking/uWebSockets
        path: uWebSockets
        submodules: true

    - name: Install dependencies
      run: |
        brew install libuv

    - name: Make
      run: |
        # Unclear if this first make is needed.
        cd uWebSockets
        make capi
        cd capi
        make

    - name: Build dynamic library
      run: |
        cd uWebSockets/capi
        clang -O3 -flto -I ../src -I ../uSockets/src *.o -lz -luv -lssl -lcrypto -lstdc++ ../uSockets/uSockets.a --shared -o libuwebsockets.dylib

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: uwebsockets-build-macos
        path: uWebSockets/capi/libuwebsockets.dylib
        if-no-files-found: error


  build-uwebsockets-linux: 
    name: Build uWebSockets (Linux)
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3.6.0
      with:
        repository: uNetworking/uWebSockets
        path: uWebSockets
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get install libuv1-dev

    - name: Make
      run: |
        # Unclear if this first make is needed.
        cd uWebSockets
        make capi
        cd capi
        make

    - name: Build dynamic library
      run: |
        cd uWebSockets/capi
        ls
        gcc -O3 -flto -I ../src -I ../uSockets/src *.o -lz -luv -lssl -lcrypto -lstdc++ ../uSockets/uSockets.a --shared -o libuwebsockets.so
        ls

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: uwebsockets-build-linux
        path: uWebSockets/capi/libuwebsockets.so
        if-no-files-found: error

  build-uwebsockets-windows: 
    name: Build uWebSockets (Windows)
    runs-on: windows-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3.6.0
      with:
        repository: uNetworking/uWebSockets
        path: uWebSockets
        submodules: true

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2

    # - name: Install dependencies
    #   run: |
    #     sudo apt-get install libuv1-dev

    - name: Make
      shell: msys2 {0}
      run: |
        cd uWebSockets
        make
        # make capi
        # cd capi
        # make

    - name: Build dynamic library
      shell: bash
      run: |
        cd uWebSockets/capi
        ls
        gcc -O3 -flto -I ../src -I ../uSockets/src *.o -lz -luv -lssl -lcrypto -lstdc++ ../uSockets/uSockets.a --shared -o libuwebsockets.dll
        ls

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: uwebsockets-build-windows
        path: uWebSockets/capi/libuwebsockets.dll
        if-no-files-found: error
    
    # - uses: actions/download-artifact@v3
    #   with:
    #     name: libffi-autogen
          
    # - name: Configure libffi
    #   shell: bash
    #   run: |
    #     tar -xvf libffi.tar
    #     cd libffi
    #     mkdir source-build
    #     cd source-build          
    #     mkdir build
    #     ../configure --disable-docs --prefix $PWD/build LDFLAGS=-Wl,-rpath,"@loader_path"
      
    # - name: Run make
    #   shell: bash
    #   run: |
    #     export SHELL="/bin/sh"
    #     cd libffi
    #     cd source-build
    #     make install
          
    # - name: Upload libffi built artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: libffi-build-Linux
    #     path: libffi/source-build/build/
    #     if-no-files-found: error
    
    # - name: Upload libffi core library artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: libffi-core-build-Linux
    #     path: libffi/source-build/build/lib/libffi.*
    #     if-no-files-found: error
        

  # final-assembly:
  #   name: Final paclet assembly
    
  #   needs:
  #   - build-libffi-linux
  #   - build-libffi-macos
  #   - build-constants-linux
  #   - build-constants-macos
    
  #   runs-on: ubuntu-latest
      
  #   steps:
      
  #   - uses: actions/checkout@v3
    
  #   - name: Download macOS libffi builds
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: libffi-core-build-macOS
  #       path: ForeignFunctionInterface/LibraryResources/MacOSX-x86-64/
        
  #   - name: Download macOS constants
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: ffiConstants-macOS
  #       path: ForeignFunctionInterface/LibraryResources/MacOSX-x86-64/
        
  #   - name: Download Linux libffi builds
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: libffi-core-build-Linux
  #       path: ForeignFunctionInterface/LibraryResources/Linux-x86-64/
        
  #   - name: Download Linux constants
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: ffiConstants-Linux
  #       path: ForeignFunctionInterface/LibraryResources/Linux-x86-64/
        
  #   - name: Upload final paclet
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: ForeignFunctionInterface
  #       path: ForeignFunctionInterface/
  #       if-no-files-found: error
    
