name: Build
on:
  pull_request:
    branches: ["master"]
  push:
  workflow_dispatch:
jobs:

  build-uwebsockets-mac-arm: 
    name: Build uWebSockets (macOS ARM)
    runs-on: macos-latest
    
    steps:

    - name: Get zlib repository
      uses: actions/checkout@v3.6.0
      with:
        repository: https://github.com/madler/zlib
        path: zlib

    - name: Build zlib
      run: |
        cd zlib
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=build
        cmake --build .
        cmake --install .

    - name: Get libuv repository
      uses: actions/checkout@v3.6.0
      with:
        repository: https://github.com/libuv/libuv
        path: libuv

    - name: Build libuv
      run: |
        cd libuv
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=build
        cmake --build .
        cmake --install .

    - name: Get repository
      uses: actions/checkout@v3.6.0

    - name: Build uWebSockets
      run: |
        mkdir build
        cd build
        cmake ..
          -DCMAKE_BUILD_TYPE=Release
          -DSYSTEM_ID=MacOSX-ARM64
          -DCMAKE_OSX_ARCHITECTURES=arm64
          -DZLIB_ROOT=zlib/build/build/
          -DLIBUV_ROOT=libuv/build/build/

    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --install build

    - uses: actions/upload-artifact@v3
      with:
        name: build-macos-arm
        path: build/WebServer
        if-no-files-found: error


  build-uwebsockets-mac: 
    name: Build uWebSockets (macOS)
    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v3.6.0

    - name: cmake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DSYSTEM_ID=MacOSX-x86-64 -DCMAKE_OSX_ARCHITECTURES=x86_64 ..

    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --install build

    - uses: actions/upload-artifact@v3
      with:
        name: build-macos
        path: build/WebServer
        if-no-files-found: error


  build-uwebsockets-linux: 
    name: Build uWebSockets (Linux)
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3.6.0

    - name: Install dependencies
      run: sudo apt install libuv1-dev

    - name: cmake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DSYSTEM_ID=Linux-x86-64 ..

    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --install build

    - uses: actions/upload-artifact@v3
      with:
        name: build-linux
        path: build/WebServer
        if-no-files-found: error


  build-uwebsockets-windows: 
    name: Build uWebSockets (Windows)
    runs-on: windows-latest
    
    steps:

    - uses: actions/checkout@v3.6.0

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Install dependencies
      run: |
        # zlib:x64-windows
        vcpkg install libuv:x64-windows
        vcpkg integrate install

    # - name: More dependencies
    #   run: vcpkg install libuv uwebsockets --triplet=x64-windows

    - name: cmake
      run: |
        mkdir build
        cd build
        # -DZLIB_LIBRARY=/usr/lib/libz.dll.a
        # cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DSYSTEM_ID=Windows-x86-64 ..
        cmake -DCMAKE_BUILD_TYPE=Release -DSYSTEM_ID=Windows-x86-64 ..

    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --install build

    - uses: actions/upload-artifact@v3
      with:
        name: build-windows
        path: build/WebServer
        if-no-files-found: error


  # build-uwebsockets-mac: 
  #   name: Build uWebSockets (macOS)
  #   runs-on: macos-latest
    
  #   steps:

  #   - uses: actions/checkout@v3.6.0
  #     with:
  #       repository: uNetworking/uWebSockets
  #       path: uWebSockets
  #       submodules: true

  #   - name: Install dependencies
  #     run: |
  #       brew install libuv

  #   - name: Make
  #     run: |
  #       # Unclear if this first make is needed.
  #       cd uWebSockets
  #       make capi
  #       cd capi
  #       make

  #   - name: Build dynamic library
  #     run: |
  #       cd uWebSockets/capi
  #       clang -O3 -flto *.o -lz -luv -lssl -lcrypto -lstdc++ ../uSockets/uSockets.a --shared -o libuwebsockets.dylib

  #   - uses: actions/upload-artifact@v3
  #     with:
  #       name: uwebsockets-build-macos
  #       path: uWebSockets/capi/libuwebsockets.dylib
  #       if-no-files-found: error


  # build-uwebsockets-mac-arm: 
  #   name: Build uWebSockets (macOS ARM)
  #   runs-on: self-hosted
    
  #   steps:

  #   - uses: actions/checkout@v3.6.0
  #     with:
  #       repository: uNetworking/uWebSockets
  #       path: uWebSockets
  #       submodules: true

  #   - name: Install dependencies
  #     run: |
  #       brew install libuv
        
  #   - name: Make
  #     run: |
  #       export CPATH=/opt/homebrew/include 
  #       export LIBRARY_PATH=/opt/homebrew/lib
        
  #       # Unclear if this first make is needed.
  #       cd uWebSockets
  #       make capi
  #       cd capi
  #       make

  #   - name: Build dynamic library
  #     run: |
  #       export CPATH=/opt/homebrew/include 
  #       export LIBRARY_PATH=/opt/homebrew/lib
        
  #       cd uWebSockets/capi
  #       clang -O3 -flto *.o -lz -luv -lssl -lcrypto -lstdc++ ../uSockets/uSockets.a --shared -o libuwebsockets.dylib

  #   - uses: actions/upload-artifact@v3
  #     with:
  #       name: uwebsockets-build-macos-arm
  #       path: uWebSockets/capi/libuwebsockets.dylib
  #       if-no-files-found: error


  # build-uwebsockets-linux: 
  #   name: Build uWebSockets (Linux)
  #   runs-on: ubuntu-latest
    
  #   steps:

  #   - uses: actions/checkout@v3.6.0
  #     with:
  #       repository: uNetworking/uWebSockets
  #       path: uWebSockets
  #       submodules: true

  #   - name: Install dependencies
  #     run: |
  #       sudo apt-get install libuv1-dev

  #   - name: Make
  #     run: |
  #       # Unclear if this first make is needed.
  #       cd uWebSockets
  #       make capi
  #       cd capi
  #       make

  #   - name: Build dynamic library
  #     run: |
  #       cd uWebSockets/capi
  #       ls
  #       gcc -O3 -flto *.o -lz -luv -lssl -lcrypto -lstdc++ ../uSockets/uSockets.a --shared -o libuwebsockets.so
  #       ls

  #   - uses: actions/upload-artifact@v3
  #     with:
  #       name: uwebsockets-build-linux
  #       path: uWebSockets/capi/libuwebsockets.so
  #       if-no-files-found: error

  # # build-uwebsockets-windows: 
  # #   name: Build uWebSockets (Windows)
  # #   runs-on: windows-latest
    
  # #   steps:

  # #   # - uses: actions/checkout@v3.6.0
  # #   #   with:
  # #   #     repository: uNetworking/uWebSockets
  # #   #     path: uWebSockets
  # #   #     submodules: true

  # #   # - name: Install libuv
  # #   #   run: |
  # #   #     vcpkg install libuv:x64-windows
  # #   #     cp C:\vcpkg\installed\x64-windows\bin\uv.dll uWebSockets\uv.dll

  # #   # - uses: ilammy/msvc-dev-cmd@v1
    
  # #   # - name: Make
  # #   #   run: |
  # #   #     cd uWebSockets
  # #   #     $Env:WITH_ZLIB='0'; $ENV:WITH_LTO='0'; $Env:CC='clang';
  # #   #     $ENV:CFLAGS='-I C:\vcpkg\installed\x64-windows\include';
  # #   #     $ENV:LDFLAGS='-L C:\vcpkg\installed\x64-windows\lib';
  # #   #     $ENV:CXX='clang++'; $ENV:EXEC_SUFFIX='.exe'; $ENV:WITH_LIBUV='1'
  # #   #     nmake
  # #   #     ls
  # #   #     ls capi
  # #   #     nmake capi
  # #   #     ls
  # #   #     cd capi
  # #   #     ls
  # #   #     nmake

  # #   # - name: Build dynamic library
  # #   #   run: |
  # #   #     cd uWebSockets/capi
  # #   #     ls
  # #   #     gcc -O3 -flto -I ../src -I ../uSockets/src *.o -lz -luv -lssl -lcrypto -lstdc++ ../uSockets/uSockets.a --shared -o libuwebsockets.dll
  # #   #     ls

  # #   - name: Install uWebSockets
  # #     run: |
  # #       vcpkg install uwebsockets
  # #       ls
  # #       ls C:\vcpkg\installed\x64-windows\

  # #   - uses: actions/upload-artifact@v3
  # #     with:
  # #       name: uwebsockets-build-windows
  # #       path: uWebSockets/capi/libuwebsockets.dll
  # #       if-no-files-found: error

  # final-assembly:
  #   name: Final paclet assembly

  #   needs:
  #     - build-uwebsockets-mac
  #     - build-uwebsockets-mac-arm
  #     - build-uwebsockets-linux

  #   runs-on: ubuntu-latest

  #   steps:
    
  #     - uses: actions/checkout@v3
  #       with:
  #         path: deployed/WebServer
  #         sparse-checkout: |
  #           Documentation
  #           Kernel
  #           PacletInfo.wl
  #           ResourceDefinition.nb

  #     - name: Download macOS uWebSockets builds
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: uwebsockets-build-macos
  #         path: deployed/WebServer/LibraryResources/MacOSX-x86-64/

  #     - name: Download macOS (ARM) uWebSockets builds
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: uwebsockets-build-macos-arm
  #         path: deployed/WebServer/LibraryResources/MacOSX-ARM64/

  #     - name: Download Linux uWebSockets builds
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: uwebsockets-build-linux
  #         path: deployed/WebServer/LibraryResources/Linux-x86-64/

  #     - name: Upload final paclet
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: WebServer
  #         path: deployed/
  #         if-no-files-found: error
    
