name: Build
on:
  pull_request:
    branches: ["master"]
  push:
  workflow_dispatch:
jobs:

  build-uwebsockets-windows:
    name: Build uWebSockets (Windows)
    runs-on: windows-latest
    steps:

      - name: Get uWebSockets repository
        uses: actions/checkout@v3.6.0
        with:
          repository: uNetworking/uWebSockets
          path: uWebSockets
          submodules: recursive
        
      - name: Install libuv
        run: |
          vcpkg install libuv:x64-windows libuv:x64-windows-static
          cp C:\vcpkg\installed\x64-windows\lib\uv.lib uWebSockets\uv.lib
          
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Run make
        run: |
          cd uWebSockets
          $ENV:WITH_ZLIB='0'; $ENV:WITH_LTO='0'; $ENV:CC='clang';
          $ENV:CFLAGS='-I C:\vcpkg\installed\x64-windows\include';
          # $ENV:LDFLAGS='-L C:\vcpkg\installed\x64-windows\lib';
          $ENV:LDFLAGS='-L D:\a\WebServer\uWebSockets';
          $ENV:CXX='clang++'; $ENV:EXEC_SUFFIX='.exe'; $ENV:WITH_LIBUV='1'; nmake

      - name: Build CAPI
        run: |
          cd uWebSockets
          clang++ -march=native -O3 -std=c++20 -Isrc -IuSockets/src -DUWS_NO_ZLIB -L D:\a\WebServer\uWebSockets uSockets/*.o -luv --shared -o libuwebsockets.dll capi/libuwebsockets.cpp
          
      - name: Print dependencies
        run: dumpbin /dependents uWebSockets/libuwebsockets.dll

      - uses: actions/upload-artifact@v3
        with:
          name: libuwebsockets-windows
          path: uWebSockets/libuwebsockets.dll
          if-no-files-found: error
        

  build-uwebsockets-mac-arm: 
    name: Build uWebSockets (macOS ARM)
    runs-on: macos-latest
    
    steps:

    - name: Get zlib repository
      uses: actions/checkout@v3.6.0
      with:
        repository: madler/zlib
        path: zlib

    - name: Build zlib
      run: |
        cd zlib
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES=arm64
        cmake --build .
        cmake --install .

    - name: Get libuv repository
      uses: actions/checkout@v3.6.0
      with:
        repository: libuv/libuv
        path: libuv

    - name: Build libuv
      run: |
        cd libuv
        mkdir build
        cd build
        cmake .. -DLIBUV_BUILD_TESTS=OFF -DLIBUV_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES=arm64
        cmake --build .
        cmake --install .

    - name: Get repository
      uses: actions/checkout@v3.6.0
      with:
        path: WebServer

    - name: Build uWebSockets
      run: |
        cd WebServer
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DSYSTEM_ID=MacOSX-ARM64 -DCMAKE_OSX_ARCHITECTURES=arm64 -DZLIB_ROOT=../../zlib/build/install/ -DLIBUV_ROOT=../../libuv/build/install/
        cmake --build .
        cmake --install .

    - uses: actions/upload-artifact@v3
      with:
        name: libuwebsockets-macos-arm
        path: WebServer/build/WebServer/LibraryResources/libuwebsockets.dylib
        if-no-files-found: error


  build-uwebsockets-mac: 
    name: Build uWebSockets (macOS)
    runs-on: macos-latest
    
    steps:

    - name: Get zlib repository
      uses: actions/checkout@v3.6.0
      with:
        repository: madler/zlib
        path: zlib

    - name: Build zlib
      run: |
        cd zlib
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES=x86_64
        cmake --build .
        cmake --install .

    - name: Get libuv repository
      uses: actions/checkout@v3.6.0
      with:
        repository: libuv/libuv
        path: libuv

    - name: Build libuv
      run: |
        cd libuv
        mkdir build
        cd build
        cmake .. -DLIBUV_BUILD_TESTS=OFF -DLIBUV_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES=x86_64
        cmake --build .
        cmake --install .

    - name: Get repository
      uses: actions/checkout@v3.6.0
      with:
        path: WebServer

    - name: Build uWebSockets
      run: |
        cd WebServer
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DSYSTEM_ID=MacOSX-x86-64 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DZLIB_ROOT=../../zlib/build/install/ -DLIBUV_ROOT=../../libuv/build/install/
        cmake --build .
        cmake --install .

    - uses: actions/upload-artifact@v3
      with:
        name: libuwebsockets-macos
        path: WebServer/build/WebServer/LibraryResources/libuwebsockets.dylib
        if-no-files-found: error


  build-uwebsockets-linux: 
    name: Build uWebSockets (Linux)
    runs-on: ubuntu-latest
    
    steps:

    - name: Get zlib repository
      uses: actions/checkout@v3.6.0
      with:
        repository: madler/zlib
        path: zlib

    - name: Build zlib
      run: |
        cd zlib
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        cmake --build .
        cmake --install .

    - name: Get libuv repository
      uses: actions/checkout@v3.6.0
      with:
        repository: libuv/libuv
        path: libuv

    - name: Build libuv
      run: |
        cd libuv
        mkdir build
        cd build
        cmake .. -DLIBUV_BUILD_TESTS=OFF -DLIBUV_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=install -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        cmake --build .
        cmake --install .

    - name: Get repository
      uses: actions/checkout@v3.6.0
      with:
        path: WebServer

    - name: Build uWebSockets
      run: |
        cd WebServer
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DSYSTEM_ID=Linux-x86-64 -DZLIB_ROOT=../../zlib/build/install/ -DLIBUV_ROOT=../../libuv/build/install/
        cmake --build .
        cmake --install .

    - uses: actions/upload-artifact@v3
      with:
        name: libuwebsockets-linux
        path: WebServer/build/WebServer/LibraryResources/libuwebsockets.so
        if-no-files-found: error
        

  final-assembly:
    name: Final paclet assembly

    needs:
      - build-uwebsockets-mac
      - build-uwebsockets-mac-arm
      - build-uwebsockets-linux
      - build-uwebsockets-windows

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
        with:
          path: deployed/WebServer
          sparse-checkout: |
            Documentation
            Kernel
            PacletInfo.wl
            ResourceDefinition.nb

      - name: Download macOS uWebSockets builds
        uses: actions/download-artifact@v3
        with:
          name: uwebsockets-build-macos
          path: deployed/WebServer/LibraryResources/MacOSX-x86-64/

      - name: Download macOS (ARM) uWebSockets builds
        uses: actions/download-artifact@v3
        with:
          name: uwebsockets-build-macos-arm
          path: deployed/WebServer/LibraryResources/MacOSX-ARM64/

      - name: Download Linux uWebSockets builds
        uses: actions/download-artifact@v3
        with:
          name: uwebsockets-build-linux
          path: deployed/WebServer/LibraryResources/Linux-x86-64/

      - name: Download Windows uWebSockets builds
        uses: actions/download-artifact@v3
        with:
          name: uwebsockets-build-linux
          path: deployed/WebServer/LibraryResources/Windows-x86-64/

      - name: Upload final paclet
        uses: actions/upload-artifact@v3
        with:
          name: WebServer
          path: deployed/
          if-no-files-found: error
